### ISSUE TITLE
Posts without tags aren't displayed in the index page

### ISSUE THREAD

**Issue by eternialz** [eternialz/moeverdose#17]
**Description**
Posts without tags aren't displayed in the index page

**To Reproduce**
1. Go to 'Posts' > 'Upload'
2. Select a new image to upload
3. Click on upload without adding any tags, characters, source or author informations

**Expected behavior**
The uploaded post should be displayed

**Comment by eternialz** [comment]
Not reproducible anymore

**Comment by Aruisehu** [comment]
Well you fixed it with #42
