### ISSUE TITLE
Copyright Management

### ISSUE THREAD

**Issue by Aruisehu** [eternialz/moeverdose#6]
Ask author a proof of his claim => what kind of proof, what if we don't know him
Ask what to do with the post (credit him, remove post)

**Comment by Aruisehu** [comment]
Maybe the best for this issue, is asking the author who will come on moeverdose for specification: what they want, what they need, etc...
But we need the basics: make a claim, enter proof, remove post, and maybe join Discord for discussion with moderators

**Comment by eternialz** [comment]
Claimer are required to create an account and verify their email address to undertake the procedure.

Procedure: 
Claimer must have multiple options
- Be credited for the work in which case we just redirect to the edit post and suggest creating an author page linked to his author tag.
    - If the claimer want and has proof of their identity, lock the post for editing
- Removal of post :
    - In this case the post will be hidden, and the uploader will have the option to remove that claim to render the post public again.
    - The claimer and uploader can claim/unclaim again indefinitely
    - Both sides can prove their identity by contacting us to justify their case. If done by the claimer, the post will be definitely deleted. If done by the uploader, the post will stay visible and can't be claimed again, the author will be locked too.

Proof of identity:
The proof can be done by contacting us

**Comment by Aruisehu** [comment]
>       * Both sides can prove their identity by contacting us to justify their case. If done by the claimer, the post will be definitely deleted. If done by the uploader, the post will stay visible and can't be claimed again, the author will be locked too.

Rare edge cases (not needed for a v1): what if we receive sufficient and convincing proofs from both side?
